# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c56fa7a28e7bf9ffe7962f45dbf5365294af766286ce020e65f7365f2365dfca4eb32234640045e099562eed555b18355f0052bc3f954116a923de7297d85b25

test:
  secret_key_base: 340b976c20c611bc01d0bef0f9e37bdd56f44400586e9eadc486f3e91a53a05aaab7de8491f192d27ec9f8e7fe1fff25b20e3075a2aa51b1423437e4e62b93d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
